language: go
services:
- docker
go:
- 1.10.x
before_install:
- curl -o- https://raw.githubusercontent.com/manifoldco/manifold-cli/master/install.sh
  | bash
- export PATH=$PATH:$HOME/.manifold/bin/
install: make bootstrap
cache:
- directories:
  - "$GOPATH/bin"
  - "$GOPATH/pkg"
branches:
  only:
  - master
  - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
script:
- manifold run -- make ci
env:
  global:
  - secure: llLkNlJ6eDLVKqo6SLf4pDbR58C3Nx5qQ6Xxlk9H/yV48UOM8twHtDKWXjIZuVKi/95mFw4TqJ7uv3k4QM9SOiGJxEvJ4rPs09cdTznxj1zsnmRTcBIWLXmCb3zySaUTiXQJ1IglZN+KzTPXqMdsDNHTuNNYFTdtGzHLyPnhQ669eAQgSDpVh5GntBjwcl7FUbYBcIoAtPUvnXkmSeXrEqanvCwfHmXoectc9EfEPLidB2FkgoMLpfgRL6fva0BHIy0DSUqWjy0JtGeivuslRJAIQCjiBuPjmNP+ObXM0+sSqe4oNhHBTz07+PneJDu00ScTpbe7++jurH5gCCu0qdXgjSUVc0E/aiws4w2ZlS3E3JwcoFqzwIK+2OY5bQhadO677PJoSt78fPLANvEuvDOC38gAdk51BtBhWuOEIBn6cvNUc62kyYKPVTLiWWbiBm2OjwAnBNrJ0xxPmveOzEKsiHOojyVjEwLJiX25jUsO99IAmaHUeg1GaopYLB0ilvJHJroKykC+P/VjJyez4SK37gu75UIYPIHkLPenckF/8pGBumT2eBOIno06sq0qMfU7qtU6xvgbR02ISjJtKTUwerlSo7hEomT9StMntvTzaVZQH5UsXYrHPR0M1VP9ZU1l0EGm3opo7kjArZ+Zfoodq09MRQB+OcxAnzYToEE=
  - secure: gaPv+WKOEAGbXpNC8yFR4dMZ4Ft3+MkiEFtiDtGPD9YguALLhk2tFILb0SI8zrd/GvjaqJtRSpbC7AmDunE9tzU0zBIfoIXO4A+skUgFN1LX8rVUG1CLtVeuo+LfgwipjOF1yJrkyXa+thGY718pay5nTaZ1vo56CU8gF6hczWxyro3bxRfrpxCEDeabL2865sbggNtCNL5iGj8zn9Ay9vdSCJnZLRYKCswcB7/hXWFKc9tIT26AOD3kiwkPK9aDbuwsxGb1e9fLrBtXgJS+tLg5pPEOXyONqrY38fbpVhPXZsy8SBp5gNs4pdNE+AJFGnzct/z0VSXii4fRb4CXnzSRDTbYdHhTPFR4WHOwiQ/xS5M4CL50lHrVWwOH4I+9C4nTAJgRq7NvIZhtxgl1VbOaS5U171anHCxPwgjvEzAmBl52OGPkG3V7bOUqKh2Pl4L3d+TGGLUpKFAIlFscySuxSGsMCIiGhGnPY+FCNZ26O3/8mWPoj6oAxh3Y2xzNqyKBKQN4CKV5jo/h31M44EgAScj7zVupbuUAukGCybMrfEYO+3P6wtucATTSCcjWGfqyGYXn1Zyyp5KIW+PVk78UawCRH/6sPOdaunqLBTMI80RKm+JmJN7OHQaoXIiUFSmPMZcLx6cmlx99sGmk3IvK5/4xVy0U7dtT2deLOFY=
