required = [
    "github.com/alecthomas/gometalinter",
    "k8s.io/code-generator/cmd/deepcopy-gen",
]

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v6.0.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.9.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"
