required = [
    "k8s.io/code-generator/cmd/deepcopy-gen",
]

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "d4e6b95c12a08b4de2d48b45d5b4d594e5d32fab"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v6.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.9.3"

[[constraint]]
  name = "github.com/jelmersnoeck/kubekit"
  branch = "patcher-add-helper"
