apiVersion: hlnr.io/v1alpha1
kind: VersioningPolicy
metadata:
  name: release-minor
spec:
  semVer:
    version: minor
    level: release

---

apiVersion: hlnr.io/v1alpha1
kind: ImagePolicy
metadata:
  name: hello-world
spec:
  image: hlnr/hello-world
  versioningPolicy:
    name: release-minor

---

apiVersion: hlnr.io/v1alpha1
kind: Microservice
metadata:
  name: hello-world
spec:
  imagePolicy:
    name: hello-world
