apiVersion: hlnr.io/v1alpha1
kind: VersioningPolicy
metadata:
  name: release-minor
spec:
  semverRef:
    version: minor
    level: release

---

apiVersion: hlnr.io/v1alpha1
kind: ImagePolicy
metadata:
  name: hello-world
spec:
  image: hlnr/hello-world
  versioningPolicy:
    name: release-minor
status:
  image: hlnr/hello-world:latest

---

apiVersion: hlnr.io/v1alpha1
kind: AvailabilityPolicy
metadata:
  name: hello-world
spec:
  replicas: 4
  minAvailable: 1
  maxUnavailable: 1
  restartPolicy: Always
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "service"
                operator: In
                values:
                - hello-maximum
          topologyKey: "kubernetes.io/hostname"
      - weight: 90
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "service"
                operator: In
                values:
                - hello-maximum
          topologyKey: "failure-domain.beta.kubernetes.io/zone"
  deploymentStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

---

apiVersion: hlnr.io/v1alpha1
kind: Microservice
metadata:
  name: hello-world
spec:
  availabilityPolicy:
    name: hello-world
  imagePolicy:
    name: hello-world
