apiVersion: hlnr.io/v1alpha1
kind: VersioningPolicy
metadata:
  name: release-minor
spec:
  semverRef:
    version: minor
    level: release

---

apiVersion: hlnr.io/v1alpha1
kind: ImagePolicy
metadata:
  name: hello-world
spec:
  image: hlnr/hello-world
  versioningPolicy:
    name: release-minor
status:
  image: hlnr/hello-world:latest

---

apiVersion: hlnr.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: hello-world
spec:
  automountServiceAccountToken: false

---

apiVersion: hlnr.io/v1alpha1
kind: ConfigPolicy
metadata:
  name: hello-world
spec:
  env:
  - name: MY_KEY
    value: MY_VALUE

---

apiVersion: hlnr.io/v1alpha1
kind: NetworkPolicy
metadata:
  name: hello-world
spec:
  ingressClass: nginx
  ports:
  - name: headless
    port: 80
    targetPort: 8080
  dns:
  - domain: hello-world.demo.cool
    ttl: 10
    disableTLS: false
    TLSGroup: hello-world
    port: headless
  - domain: unsecure-hello-world.demo.cool
    ttl: 10
    disableTLS: true
    port: headless

---

apiVersion: hlnr.io/v1alpha1
kind: AvailabilityPolicy
metadata:
  name: hello-world
spec:
  replicas: 4
  minAvailable: 1
  restartPolicy: Always
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "service"
                operator: In
                values:
                - hello-maximum
          topologyKey: "kubernetes.io/hostname"
      - weight: 90
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "service"
                operator: In
                values:
                - hello-maximum
          topologyKey: "failure-domain.beta.kubernetes.io/zone"
  deploymentStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

---

apiVersion: hlnr.io/v1alpha1
kind: Microservice
metadata:
  name: hello-world
spec:
  availabilityPolicy:
    name: hello-world
  networkPolicy:
    name: hello-world
  imagePolicy:
    name: hello-world
  configPolicy:
    name: hello-world
  securityPolicy:
    name: hello-world
