apiVersion: hglnr.io/v1alpha1
kind: VersionedMicroservice
metadata:
  name: hello-world-minimum
spec:
  network:
    dns:
      domain: hello-world.demo.cool
  containers:
  - name: hello-world
    image: hglnrio/hello-world:latest
    imagePullPolicy: IfNotPresent
