apiVersion: hlnr.io/v1alpha1
kind: VersionedMicroservice
metadata:
  labels:
    service: hello-maximum
    component: world
  name: hello-world-maximum
spec:
  availability:
    replicas: 2
    minAvailable: 1
    maxUnavailable: 1
    restartPolicy: Always
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: "service"
                  operator: In
                  values:
                  - hello-maximum
            topologyKey: "kubernetes.io/hostname"
        - weight: 90
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: "service"
                  operator: In
                  values:
                  - hello-maximum
            topologyKey: "failure-domain.beta.kubernetes.io/zone"
    deploymentStrategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
  network:
    ports:
    - name: headless
      externalPort: 80
      internalPort: 8080
    dns:
    - domain: hello-world.demo.cool
      ttl: 10
      disableTLS: false
      TLSGroup: hello-world
      port: headless
    - domain: unsecure-hello-world.demo.cool
      ttl: 10
      disableTLS: true
      port: headless
  volumes:
  - name: jwt-public
    emptyDir: {}
  containers:
  - name: hello-world
    image: hlnr/hello-world:latest
    imagePullPolicy: Never
    readinessProbe:
      httpGet:
        path: /_healthz
        port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
    livenessProbe:
      httpGet:
        path: /_healthz
        port: 8080
        initialDelaySeconds: 5
        periodSeconds: 3
    volumeMounts:
    - name: jwt-public
      mountPath: /jwt
      readOnly: true
