apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: heighliner:github-policy
rules:
  - apiGroups: ["hlnr.io"]
    resources: ["githubpolicies"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heighliner:github-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heighliner:github-policy
subjects:
  - name: heighliner-github-policy
    namespace: hlnr-system
    kind: ServiceAccount

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: heighliner-github-policy
  namespace: hlnr-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: github-policy-controller
  namespace: hlnr-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: github-policy-controller
    spec:
      serviceAccountName: heighliner-github-policy
      containers:
        - name: github-policy-controller
          image: arigato/heighliner:latest
          imagePullPolicy: Never
          args:
          - github-policy-controller
          env:
            - name: DOMAIN
              value: f22d1449.ngrok.io
            - name: INSECURE_SSL
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: github-policy-controller
  name: github-policy-controller
  namespace: hlnr-system
spec:
  type: NodePort
  ports:
  - name: headless
    port: 80
    targetPort: 8080
  selector:
    app: github-policy-controller
status:
  loadBalancer: {}

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: github-policy-controller
  namespace: hlnr-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: f22d1449.ngrok.io
    http:
      paths:
      - path: /
        backend:
          serviceName: github-policy-controller
          servicePort: 80
  - host: github-policy-controller.arigato.tools
    http:
      paths:
      - path: /
        backend:
          serviceName: github-policy-controller
          servicePort: 80
