apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: heighliner:image-policy
rules:
  - apiGroups: ["hlnr.io"]
    resources:
    - "imagepolicies"
    - "githubrepositories"
    - "versioningpolicies"
    verbs: ["*"]
  - apiGroups: ["hlnr.io"]
    resources: ["microservices"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
  - apiGroups:  [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heighliner:image-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heighliner:image-policy
subjects:
  - name: heighliner-image-policy
    namespace: hlnr-system
    kind: ServiceAccount

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: heighliner-image-policy
  namespace: hlnr-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image-policy-controller
  namespace: hlnr-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: image-policy-controller
    spec:
      serviceAccountName: heighliner-image-policy
      containers:
        - name: image-policy-controller
          image: arigato/heighliner:latest
          imagePullPolicy: IfNotPresent
          args:
          - ipc
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
