apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: heighliner:microservice
rules:
  - apiGroups: ["hlnr.io"]
    resources: ["microservices"]
    verbs: ["*"]
  - apiGroups: ["hlnr.io"]
    resources: ["versionedmicroservices"]
    verbs: ["get", "update", "create", "delete", "patch"]
  - apiGroups: ["hlnr.io"]
    resources:
    - "imagepolicies"
    - "availabilitypolicies"
    - "configpolicies"
    - "securitypolicies"
    verbs: ["get", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heighliner:microservice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heighliner:microservice
subjects:
  - name: heighliner-microservice
    namespace: hlnr-system
    kind: ServiceAccount

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: heighliner-microservice
  namespace: hlnr-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice-controller
  namespace: hlnr-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-controller
    spec:
      serviceAccountName: heighliner-microservice
      containers:
        - name: microservice-controller
          image: arigato/heighliner:{{.Version}}
          imagePullPolicy: Never
          args:
          - msvc
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
