apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: heighliner:versionedmicroservice
rules:
  - apiGroups: ["hlnr.io"]
    resources: ["versionedmicroservices"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heighliner:versionedmicroservice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heighliner:versionedmicroservice
subjects:
  - name: heighliner-versionedmicroservice
    namespace: hlnr-system
    kind: ServiceAccount

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: heighliner-versionedmicroservice
  namespace: hlnr-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: versioned-microservice-controller
  namespace: hlnr-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: versioned-microservice-controller
    spec:
      serviceAccountName: heighliner-versionedmicroservice
      containers:
        - name: versioned-microservice-controller
          image: arigato/heighliner:latest
          imagePullPolicy: IfNotPresent
          args:
          - vsvc
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
