apiVersion: hlnr.io/v1alpha1
kind: GitHubPolicy
metadata:
  name: heighliner-www
  namespace: websites
spec:
  maxAvailable: 1
  repositories:
  - name: heighliner-www
    owner: manifoldco
    configSecret:
      name: manifold-github
status: {}
